package dk.statsbiblioteket.broadcasttranscoder.processors;

import org.junit.Test;

import java.io.File;

public class SnapshotExtractorProcessorTest {

    @Test
    public void createCommandline() {
//        This is just a utility to let you see what the commandline generated by the system
//        This is nessesary, as the options are dependent on length and other properties
        SnapshotExtractorProcessor processor = new SnapshotExtractorProcessor();
        String cmdln = processor.createCommandline(
                16,
                9,
                26,
                120,
                5,
                new File("/home/bta/streamingContent/6a844744-45ba-486d-902e-b552c0e89d4f.flv"),
                25*60,
                "/home/larm/imageDirectory/6a844744-45ba-486d-902e-b552c0e89d4f.%d.png"
        );
        System.out.println(cmdln);
    }
}